import { NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/server'
import { sendSurveyEmail } from '@/lib/email'
import { sendWA } from '@/lib/whatsapp'
import { smsSurveyInvitation } from '@/lib/sms'

// Vercel Cron Job — runs daily at 04:00 UTC (07:00 Israel time)
// Sends placement satisfaction surveys 30 days after a candidate was placed.
// Uses a 30–31 day window so a re-run on the same day is a no-op (idempotent).
export async function GET(request: Request) {
  const authHeader = request.headers.get('authorization')
  const cronSecret = process.env.CRON_SECRET
  if (!cronSecret || authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const service = createServiceClient()
  const now = new Date()

  // placement_date is stored as DATE (YYYY-MM-DD)
  const thirtyDaysAgo    = new Date(now.getTime() - 30 * 86_400_000).toISOString().slice(0, 10)
  const thirtyOneDaysAgo = new Date(now.getTime() - 31 * 86_400_000).toISOString().slice(0, 10)

  const { data: placements, error } = await service
    .from('applications')
    .select(`
      id,
      candidates(profile_id, profiles(full_name, phone)),
      jobs(title, institutions(profile_id, institution_name, profiles(full_name, phone)))
    `)
    .eq('status', 'התקבלה')
    .gte('placement_date', thirtyOneDaysAgo)
    .lte('placement_date', thirtyDaysAgo)

  if (error) {
    console.error('[CRON] placement-surveys fetch error:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  if (!placements?.length) {
    return NextResponse.json({ ok: true, sent: 0 })
  }

  // Idempotency: skip applications that already have surveys
  const appIds = placements.map(p => p.id)
  const { data: existing } = await service
    .from('placement_surveys')
    .select('application_id')
    .in('application_id', appIds)

  const alreadySent = new Set((existing ?? []).map(s => s.application_id))

  let sent = 0

  for (const placement of placements) {
    if (alreadySent.has(placement.id)) continue

    const candidate = placement.candidates as unknown as {
      profile_id: string
      profiles: { full_name: string | null; phone: string | null }
    } | null

    const job = placement.jobs as unknown as {
      title: string
      institutions: {
        profile_id: string
        institution_name: string
        profiles: { full_name: string | null; phone: string | null }
      } | null
    } | null

    if (!candidate || !job?.institutions) {
      console.warn('[CRON] placement-surveys: missing data for application', placement.id)
      continue
    }

    const candidateProfileId   = candidate.profile_id
    const candidateName        = candidate.profiles?.full_name ?? 'מועמדת'
    const candidatePhone       = candidate.profiles?.phone ?? null
    const institutionProfileId = job.institutions.profile_id
    const institutionName      = job.institutions.institution_name
    const principalName        = job.institutions.profiles?.full_name ?? institutionName
    const institutionPhone     = job.institutions.profiles?.phone ?? null

    // Insert both survey records — token is auto-generated by DB default
    const { data: surveys, error: insertErr } = await service
      .from('placement_surveys')
      .insert([
        {
          application_id:        placement.id,
          survey_type:           'candidate_about_institution',
          respondent_profile_id: candidateProfileId,
        },
        {
          application_id:        placement.id,
          survey_type:           'institution_about_candidate',
          respondent_profile_id: institutionProfileId,
        },
      ])
      .select('survey_type, token')

    if (insertErr || !surveys) {
      console.error('[CRON] placement-surveys insert failed:', placement.id, insertErr)
      continue
    }

    const candidateSurvey   = surveys.find(s => s.survey_type === 'candidate_about_institution')
    const institutionSurvey = surveys.find(s => s.survey_type === 'institution_about_candidate')

    if (candidateSurvey) {
      const surveyUrl = `${process.env.NEXT_PUBLIC_APP_URL}/survey?t=${candidateSurvey.token}`
      const waMsg = `שלום ${candidateName.split(' ')[0]} 👋\nמילאת תפקיד ב${institutionName} לפני כחודש.\nנשמח לשמוע את חוות דעתך — שאלון קצר (2 דקות):\n${surveyUrl}`
      // WhatsApp first
      if (candidatePhone) {
        try { await sendWA(candidatePhone, waMsg) } catch { /* fallback to email */ }
      }
      // Email
      try {
        await sendSurveyEmail({
          profileId:      candidateProfileId,
          recipientName:  candidateName,
          surveyType:     'candidate_about_institution',
          otherPartyName: institutionName,
          token:          candidateSurvey.token,
        })
      } catch (err) {
        console.error('[CRON] placement-surveys email to candidate failed:', candidateProfileId, err)
      }
      // SMS fallback
      if (candidatePhone) {
        try { smsSurveyInvitation(candidatePhone, candidateSurvey.token, institutionName) } catch { /* ignore */ }
      }
    }

    if (institutionSurvey) {
      const surveyUrl = `${process.env.NEXT_PUBLIC_APP_URL}/survey?t=${institutionSurvey.token}`
      const waMsg = `שלום ${principalName.split(' ')[0]} 👋\n${candidateName} שובצה אצלכם לפני כחודש.\nנשמח לשמוע את חוות דעתכם — שאלון קצר (2 דקות):\n${surveyUrl}`
      // WhatsApp first
      if (institutionPhone) {
        try { await sendWA(institutionPhone, waMsg) } catch { /* fallback to email */ }
      }
      // Email
      try {
        await sendSurveyEmail({
          profileId:      institutionProfileId,
          recipientName:  principalName,
          surveyType:     'institution_about_candidate',
          otherPartyName: candidateName,
          token:          institutionSurvey.token,
        })
      } catch (err) {
        console.error('[CRON] placement-surveys email to institution failed:', institutionProfileId, err)
      }
      // SMS fallback
      if (institutionPhone) {
        try { smsSurveyInvitation(institutionPhone, institutionSurvey.token, candidateName) } catch { /* ignore */ }
      }
    }

    sent++
  }

  return NextResponse.json({ ok: true, sent })
}
